version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres-car-agent
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: car_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 10s
      timeout: 5s
      retries: 5

  car-agent:
    build: .
    container_name: car-agent
    volumes:
      - .:/car_agent
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    tty: true

volumes:
  pgdata:
